{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MGLM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MGLM/MGLM_{{ version }}.tar.gz
  sha256: aed900e67f6aa30f1f5da2220a7621fdaad2428697bf4be4a68f9192b29d6d3a

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('MGLM')"           # [not win]
    - "\"%R%\" -e \"library('MGLM')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MGLM
  license: GPL-2.0-or-later
  summary: 'Provides functions that (1) fit multivariate discrete distributions, (2) generate random numbers from multivariate discrete distributions, and (3) run regression and penalized regression on the multivariate categorical response data.  Implemented models include: multinomial logit model, Dirichlet multinomial
    model, generalized Dirichlet multinomial model, and negative multinomial model. Making the best of the minorization-maximization (MM) algorithm and Newton-Raphson method, we derive and implement stable and efficient algorithms to find the maximum likelihood estimates. On a multi-core machine, multi-threading is supported.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: MGLM
# Version: 0.2.0
# Date: 2018-10-19
# Title: Multivariate Response Generalized Linear Models
# Author: Yiwen Zhang <zhangyiwen1015@gmail.com> and Hua Zhou <huazhou@ucla.edu>
# Maintainer: Juhyun Kim <juhkim111@ucla.edu>
# Depends: R (>= 3.0.0)
# Imports: methods, stats, parallel, stats4
# Suggests: ggplot2, plyr, reshape2, knitr
# Description: Provides functions that (1) fit multivariate discrete distributions, (2) generate random numbers from multivariate discrete distributions, and (3) run regression and penalized regression on the multivariate categorical response data.  Implemented models include: multinomial logit model, Dirichlet multinomial model, generalized Dirichlet multinomial model, and negative multinomial model. Making the best of the minorization-maximization (MM) algorithm and Newton-Raphson method, we derive and implement stable and efficient algorithms to find the maximum likelihood estimates. On a multi-core machine, multi-threading is supported.
# VignetteBuilder: knitr
# LazyLoad: yes
# LazyData: yes
# Repository: CRAN
# License: GPL (>= 2)
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-10-19 16:32:58 UTC; juhyun-kim
# Date/Publication: 2018-10-19 17:20:03 UTC
