appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZelFNBjjVrh8iRBZ7wnaDYXebs4znZRjLn5BXcWlCo+oKpdl2yJ56rCwPluZEJhn2xxPDT46vtL2gonk0/iAq79s1DrpSDOrxhroGD2H6sK4Tu2fuDBj7/SH2OmzKpGorBYvdF8L6vhP+RpCaP1LTqkYs1K6UFWgR9yz+wzBF7eO9k9p6q5u7Ww/gh065/LRWRY1uCrnR1bv1n1CaehuJ3kPez/wTVj+A9JVfGQrBZc0t0+0tg5ix8+ne4MImVCyRjUE4H/FaZbmRq6YmCKh9yFB8wuebd5AFfmfZfXddHqHpZ7FucnC3I0aWu8DVSL5U8h74O1ae07tjj5SJhq4VpgU28BdkrcH7BYflAS7mW/Et4LRf1oi0pjU8I3TvhOiz8ECv0rTw7eDC2MmiLghb0hnvsjRASgIAmf9i3yDhqDI6nxvmlhPHWGw63cRK9oS7rsM5EOwKfKO5IEP+BC4vFQ2REvL24Ts2WAaUEV9ofgHIuUAaMW+Vfr4KNbw9VceFgGBeBHEffrCOceeJpqOkmd1D8EIJ5NoO1WDhgsqJrk4reQC5t/KLls5LAji+6j8+EIOOWS9oVGFAEBbPADd5v7tqcGqEqHmPiF1rKrTqMtSVzTzdjJfNjRu1DuNeBo1rZCZ6equdoYnS14nux9NwLMXPWnaYOG8c1xZfkfILYs=
conda_forge_output_validation: true
